# Generated by Django 3.2.12 on 2022-02-13 07:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='ci',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='Entre un carnet de identidad válido(11 dígitos)')], verbose_name='Carnet de identidad'),
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Description del problema')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
