# Generated by Django 3.2.12 on 2022-02-13 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balita', '0002_auto_20220213_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creado')),
                ('motive', models.TextField(max_length=250, verbose_name='Motivo del reporte')),
                ('balita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balita.balita', verbose_name='Producto (Balita de Gas)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Entregador')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InformeReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creado')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad de balitas')),
                ('balita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balita.balita', verbose_name='Producto (Balita de Gas)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Entregador')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InformeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creado')),
                ('receiver', models.CharField(max_length=100, verbose_name='Nombre del recibidor')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad de balitas')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Importe total')),
                ('balita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balita.balita', verbose_name='Producto (Balita de Gas)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Entregador')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='Informe',
        ),
    ]
