# Generated by Django 3.2.12 on 2022-02-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balita', '0004_auto_20220214_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informereserva',
            name='date_to_reserve',
            field=models.DateField(blank=True, null=True, verbose_name='Reservar para'),
        ),
    ]
